version: '2'
services:
  mysql:
    image: hub.zentao.net/app/mysql:8.0.33-debian-11-r11
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - 'db:/bitnami/mysql/data'
    environment:
      - MYSQL_ROOT_PASSWORD=pass4GitFox
      - MYSQL_DATABASE=gitfox

  gitfox:
    image: hub.zentao.net/app/gitfox:dev
    container_name: gitfox
    pull_policy: always
    ports:
      - '3000:3000'
    volumes:
      - 'gitfox_data:/data'
      #- '/var/run/docker.sock:/var/run/docker.sock'
    depends_on:
      - mysql
    environment:
      - GITFOX_DATABASE_DRIVER=mysql
      - GITFOX_DATABASE_HOST=mysql
      - GITFOX_DATABASE_PORT=3306
      - GITFOX_DATABASE_USERNAME=root
      - GITFOX_DATABASE_PASSWORD=pass4GitFox
      - GITFOX_DATABASE_DBNAME=gitfox
      - GITFOX_DATABASE_EXTRA_OPTIONS=""
      - GITFOX_PRINCIPAL_ADMIN_EMAIL=admin@gitfox.io
      - GITFOX_PRINCIPAL_ADMIN_PASSWORD=changeit

volumes:
  db:
    driver: local
  gitfox_data:
    driver: local
