// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"

	aiagent2 "github.com/easysoft/gitfox/app/api/controller/aiagent"
	capabilities2 "github.com/easysoft/gitfox/app/api/controller/capabilities"
	check2 "github.com/easysoft/gitfox/app/api/controller/check"
	connector2 "github.com/easysoft/gitfox/app/api/controller/connector"
	"github.com/easysoft/gitfox/app/api/controller/execution"
	"github.com/easysoft/gitfox/app/api/controller/githook"
	gitspace2 "github.com/easysoft/gitfox/app/api/controller/gitspace"
	infraprovider3 "github.com/easysoft/gitfox/app/api/controller/infraprovider"
	keywordsearch2 "github.com/easysoft/gitfox/app/api/controller/keywordsearch"
	"github.com/easysoft/gitfox/app/api/controller/limiter"
	logs2 "github.com/easysoft/gitfox/app/api/controller/logs"
	migrate2 "github.com/easysoft/gitfox/app/api/controller/migrate"
	"github.com/easysoft/gitfox/app/api/controller/pipeline"
	"github.com/easysoft/gitfox/app/api/controller/plugin"
	"github.com/easysoft/gitfox/app/api/controller/principal"
	pullreq2 "github.com/easysoft/gitfox/app/api/controller/pullreq"
	"github.com/easysoft/gitfox/app/api/controller/repo"
	"github.com/easysoft/gitfox/app/api/controller/reposettings"
	"github.com/easysoft/gitfox/app/api/controller/runner"
	"github.com/easysoft/gitfox/app/api/controller/secret"
	"github.com/easysoft/gitfox/app/api/controller/service"
	"github.com/easysoft/gitfox/app/api/controller/serviceaccount"
	"github.com/easysoft/gitfox/app/api/controller/space"
	"github.com/easysoft/gitfox/app/api/controller/system"
	"github.com/easysoft/gitfox/app/api/controller/template"
	"github.com/easysoft/gitfox/app/api/controller/trigger"
	"github.com/easysoft/gitfox/app/api/controller/upload"
	"github.com/easysoft/gitfox/app/api/controller/user"
	usergroup2 "github.com/easysoft/gitfox/app/api/controller/usergroup"
	webhook2 "github.com/easysoft/gitfox/app/api/controller/webhook"
	"github.com/easysoft/gitfox/app/api/openapi"
	"github.com/easysoft/gitfox/app/artifact"
	"github.com/easysoft/gitfox/app/artifact/controller"
	"github.com/easysoft/gitfox/app/auth/authn"
	"github.com/easysoft/gitfox/app/auth/authz"
	"github.com/easysoft/gitfox/app/bootstrap"
	"github.com/easysoft/gitfox/app/connector"
	events6 "github.com/easysoft/gitfox/app/events/git"
	events7 "github.com/easysoft/gitfox/app/events/gitspace"
	events3 "github.com/easysoft/gitfox/app/events/gitspaceinfra"
	events4 "github.com/easysoft/gitfox/app/events/pipeline"
	events5 "github.com/easysoft/gitfox/app/events/pullreq"
	events2 "github.com/easysoft/gitfox/app/events/repo"
	"github.com/easysoft/gitfox/app/gitspace/infrastructure"
	"github.com/easysoft/gitfox/app/gitspace/logutil"
	"github.com/easysoft/gitfox/app/gitspace/orchestrator"
	"github.com/easysoft/gitfox/app/gitspace/orchestrator/container"
	git2 "github.com/easysoft/gitfox/app/gitspace/orchestrator/git"
	"github.com/easysoft/gitfox/app/gitspace/orchestrator/ide"
	user2 "github.com/easysoft/gitfox/app/gitspace/orchestrator/user"
	"github.com/easysoft/gitfox/app/gitspace/scm"
	secret2 "github.com/easysoft/gitfox/app/gitspace/secret"
	"github.com/easysoft/gitfox/app/pipeline/canceler"
	"github.com/easysoft/gitfox/app/pipeline/commit"
	"github.com/easysoft/gitfox/app/pipeline/converter"
	"github.com/easysoft/gitfox/app/pipeline/file"
	"github.com/easysoft/gitfox/app/pipeline/manager"
	"github.com/easysoft/gitfox/app/pipeline/resolver"
	runner2 "github.com/easysoft/gitfox/app/pipeline/runner"
	"github.com/easysoft/gitfox/app/pipeline/scheduler"
	storage2 "github.com/easysoft/gitfox/app/pipeline/storage"
	"github.com/easysoft/gitfox/app/pipeline/triggerer"
	"github.com/easysoft/gitfox/app/router"
	server2 "github.com/easysoft/gitfox/app/server"
	"github.com/easysoft/gitfox/app/services"
	"github.com/easysoft/gitfox/app/services/aiagent"
	"github.com/easysoft/gitfox/app/services/artifactgc"
	"github.com/easysoft/gitfox/app/services/capabilities"
	"github.com/easysoft/gitfox/app/services/cleanup"
	"github.com/easysoft/gitfox/app/services/codecomments"
	"github.com/easysoft/gitfox/app/services/codeowners"
	"github.com/easysoft/gitfox/app/services/exporter"
	"github.com/easysoft/gitfox/app/services/gitspace"
	"github.com/easysoft/gitfox/app/services/gitspaceevent"
	"github.com/easysoft/gitfox/app/services/gitspaceinfraevent"
	"github.com/easysoft/gitfox/app/services/importer"
	infraprovider2 "github.com/easysoft/gitfox/app/services/infraprovider"
	"github.com/easysoft/gitfox/app/services/instrument"
	"github.com/easysoft/gitfox/app/services/keywordsearch"
	"github.com/easysoft/gitfox/app/services/label"
	"github.com/easysoft/gitfox/app/services/locker"
	"github.com/easysoft/gitfox/app/services/messaging"
	"github.com/easysoft/gitfox/app/services/metric"
	"github.com/easysoft/gitfox/app/services/migrate"
	"github.com/easysoft/gitfox/app/services/notification"
	"github.com/easysoft/gitfox/app/services/notification/mailer"
	"github.com/easysoft/gitfox/app/services/protection"
	"github.com/easysoft/gitfox/app/services/publicaccess"
	"github.com/easysoft/gitfox/app/services/publickey"
	"github.com/easysoft/gitfox/app/services/pullreq"
	repo2 "github.com/easysoft/gitfox/app/services/repo"
	"github.com/easysoft/gitfox/app/services/settings"
	system2 "github.com/easysoft/gitfox/app/services/system"
	trigger2 "github.com/easysoft/gitfox/app/services/trigger"
	"github.com/easysoft/gitfox/app/services/usergroup"
	"github.com/easysoft/gitfox/app/services/webhook"
	"github.com/easysoft/gitfox/app/sse"
	"github.com/easysoft/gitfox/app/store"
	"github.com/easysoft/gitfox/app/store/cache"
	"github.com/easysoft/gitfox/app/store/database"
	"github.com/easysoft/gitfox/app/store/logs"
	"github.com/easysoft/gitfox/app/url"
	"github.com/easysoft/gitfox/audit"
	"github.com/easysoft/gitfox/blob"
	"github.com/easysoft/gitfox/cli/operations/server"
	"github.com/easysoft/gitfox/encrypt"
	"github.com/easysoft/gitfox/events"
	"github.com/easysoft/gitfox/git"
	"github.com/easysoft/gitfox/git/api"
	"github.com/easysoft/gitfox/git/storage"
	"github.com/easysoft/gitfox/infraprovider"
	"github.com/easysoft/gitfox/internal/runner/extend"
	"github.com/easysoft/gitfox/job"
	"github.com/easysoft/gitfox/livelog"
	"github.com/easysoft/gitfox/lock"
	"github.com/easysoft/gitfox/pubsub"
	"github.com/easysoft/gitfox/ssh"
	"github.com/easysoft/gitfox/store/database/dbtx"
	"github.com/easysoft/gitfox/types"
	"github.com/easysoft/gitfox/types/check"

	_ "github.com/go-sql-driver/mysql"

	_ "github.com/lib/pq"

	_ "github.com/mattn/go-sqlite3"
)

// Injectors from wire.go:

func initSystem(ctx context.Context, config *types.Config) (*server.System, error) {
	databaseConfig := server.ProvideDatabaseConfig(config)
	db, err := database.ProvideDatabase(ctx, databaseConfig)
	if err != nil {
		return nil, err
	}
	gormDB, err := database.ProvideGormDatabase(ctx, databaseConfig, config, db)
	if err != nil {
		return nil, err
	}
	transactor := dbtx.ProvideOrmTransactor(gormDB)
	principalUID := check.ProvidePrincipalUIDCheck()
	spacePathTransformation := store.ProvidePathTransformation()
	spacePathStore := database.ProvideSpacePathStore(gormDB, spacePathTransformation)
	spacePathCache := cache.ProvidePathCache(spacePathStore, spacePathTransformation)
	spaceStore := database.ProvideSpaceStore(gormDB, spacePathCache, spacePathStore)
	principalInfoView := database.ProvidePrincipalInfoView(gormDB)
	principalInfoCache := cache.ProvidePrincipalInfoCache(principalInfoView)
	membershipStore := database.ProvideMembershipStore(gormDB, principalInfoCache, spacePathStore, spaceStore)
	permissionCache := authz.ProvidePermissionCache(spaceStore, membershipStore)
	publicAccessStore := database.ProvidePublicAccessStore(gormDB)
	repoStore := database.ProvideRepoStore(gormDB, spacePathCache, spacePathStore, spaceStore)
	publicaccessService := publicaccess.ProvidePublicAccess(config, publicAccessStore, repoStore, spaceStore)
	authorizer := authz.ProvideAuthorizer(permissionCache, spaceStore, publicaccessService)
	principalUIDTransformation := store.ProvidePrincipalUIDTransformation()
	principalStore := database.ProvidePrincipalStore(gormDB, principalUIDTransformation)
	tokenStore := database.ProvideTokenStore(gormDB)
	publicKeyStore := database.ProvidePublicKeyStore(gormDB)
	userController := user.ProvideController(transactor, principalUID, authorizer, principalStore, tokenStore, membershipStore, publicKeyStore)
	serviceController := service.NewController(principalUID, authorizer, principalStore)
	bootstrapBootstrap := bootstrap.ProvideBootstrap(config, userController, serviceController)
	authenticator := authn.ProvideAuthenticators(config, principalStore, tokenStore)
	provider, err := url.ProvideURLProvider(config)
	if err != nil {
		return nil, err
	}
	pipelineStore := database.ProvidePipelineStore(gormDB)
	executionStore := database.ProvideExecutionStore(gormDB)
	ruleStore := database.ProvideRuleStore(gormDB, principalInfoCache)
	checkStore := database.ProvideCheckStore(gormDB, principalInfoCache)
	pullReqStore := database.ProvidePullReqStore(gormDB, principalInfoCache)
	settingsStore := database.ProvideSettingsStore(gormDB)
	settingsService := settings.ProvideService(settingsStore, ruleStore)
	protectionManager, err := protection.ProvideManager(ruleStore)
	if err != nil {
		return nil, err
	}
	typesConfig := server.ProvideGitConfig(config)
	universalClient, err := server.ProvideRedis(config)
	if err != nil {
		return nil, err
	}
	cacheCache, err := api.ProvideLastCommitCache(typesConfig, universalClient)
	if err != nil {
		return nil, err
	}
	clientFactory := githook.ProvideFactory()
	apiGit, err := git.ProvideGITAdapter(typesConfig, cacheCache, clientFactory)
	if err != nil {
		return nil, err
	}
	storageStore := storage.ProvideLocalStore()
	gitInterface, err := git.ProvideService(typesConfig, apiGit, clientFactory, storageStore)
	if err != nil {
		return nil, err
	}
	triggerStore := database.ProvideTriggerStore(gormDB)
	encrypter, err := encrypt.ProvideEncrypter(config)
	if err != nil {
		return nil, err
	}
	jobStore := database.ProvideJobStore(gormDB)
	pubsubConfig := server.ProvidePubsubConfig(config)
	pubSub := pubsub.ProvidePubSub(pubsubConfig, universalClient)
	executor := job.ProvideExecutor(jobStore, pubSub)
	lockConfig := server.ProvideLockConfig(config)
	mutexManager := lock.ProvideMutexManager(lockConfig, universalClient)
	jobConfig := server.ProvideJobsConfig(config)
	jobScheduler, err := job.ProvideScheduler(jobStore, executor, mutexManager, pubSub, jobConfig)
	if err != nil {
		return nil, err
	}
	streamer := sse.ProvideEventsStreaming(pubSub)
	localIndexSearcher := keywordsearch.ProvideLocalIndexSearcher()
	indexer := keywordsearch.ProvideIndexer(localIndexSearcher)
	auditService := audit.ProvideAuditService()
	repository, err := importer.ProvideRepoImporter(config, provider, gitInterface, transactor, repoStore, pipelineStore, triggerStore, encrypter, jobScheduler, executor, streamer, indexer, publicaccessService, auditService)
	if err != nil {
		return nil, err
	}
	codeownersConfig := server.ProvideCodeOwnerConfig(config)
	usergroupResolver := usergroup.ProvideUserGroupResolver()
	codeownersService := codeowners.ProvideCodeOwners(gitInterface, repoStore, codeownersConfig, principalStore, usergroupResolver)
	eventsConfig := server.ProvideEventsConfig(config)
	eventsSystem, err := events.ProvideSystem(eventsConfig, universalClient)
	if err != nil {
		return nil, err
	}
	reporter, err := events2.ProvideReporter(eventsSystem)
	if err != nil {
		return nil, err
	}
	resourceLimiter, err := limiter.ProvideLimiter()
	if err != nil {
		return nil, err
	}
	lockerLocker := locker.ProvideLocker(mutexManager)
	repoIdentifier := check.ProvideRepoIdentifierCheck()
	repoCheck := repo.ProvideRepoCheck()
	labelStore := database.ProvideLabelStore(gormDB)
	labelValueStore := database.ProvideLabelValueStore(gormDB)
	pullReqLabelAssignmentStore := database.ProvidePullReqLabelStore(gormDB)
	labelService := label.ProvideLabel(transactor, spaceStore, labelStore, labelValueStore, pullReqLabelAssignmentStore)
	instrumentService := instrument.ProvideService()
	userGroupStore := database.ProvideUserGroupStore(gormDB)
	searchService := usergroup.ProvideSearchService()
	repoController := repo.ProvideController(config, transactor, provider, authorizer, repoStore, spaceStore, membershipStore, pipelineStore, principalStore, executionStore, ruleStore, checkStore, pullReqStore, settingsService, principalInfoCache, protectionManager, gitInterface, repository, codeownersService, reporter, indexer, resourceLimiter, lockerLocker, auditService, mutexManager, repoIdentifier, repoCheck, publicaccessService, labelService, instrumentService, userGroupStore, searchService)
	aiStore := database.ProvideAIStore(gormDB)
	reposettingsController := reposettings.ProvideController(authorizer, repoStore, aiStore, settingsService, auditService, reporter)
	stageStore := database.ProvideStageStore(gormDB)
	schedulerScheduler, err := scheduler.ProvideScheduler(stageStore, mutexManager)
	if err != nil {
		return nil, err
	}
	stepStore := database.ProvideStepStore(gormDB)
	cancelerCanceler := canceler.ProvideCanceler(executionStore, streamer, repoStore, schedulerScheduler, stageStore, stepStore)
	commitService := commit.ProvideService(gitInterface)
	fileService := file.ProvideService(gitInterface)
	converterService := converter.ProvideService(fileService, publicaccessService)
	templateStore := database.ProvideTemplateStore(gormDB)
	pluginStore := database.ProvidePluginStore(gormDB)
	triggererTriggerer := triggerer.ProvideTriggerer(executionStore, checkStore, stageStore, transactor, pipelineStore, fileService, converterService, schedulerScheduler, repoStore, provider, templateStore, pluginStore, publicaccessService)
	storageConfig := server.ProvideStorageConfig(config)
	pipelineStorage, err := storage2.ProvidePipelineStorage(ctx, config, storageConfig)
	if err != nil {
		return nil, err
	}
	executionController := execution.ProvideController(transactor, authorizer, executionStore, checkStore, cancelerCanceler, commitService, triggererTriggerer, repoStore, stageStore, pipelineStore, pipelineStorage)
	logStore := logs.ProvideLogStore(gormDB, config)
	logStream := livelog.ProvideLogStream()
	logsController := logs2.ProvideController(authorizer, executionStore, repoStore, pipelineStore, stageStore, stepStore, logStore, logStream)
	spaceIdentifier := check.ProvideSpaceIdentifierCheck()
	secretStore := database.ProvideSecretStore(gormDB)
	connectorStore := database.ProvideConnectorStore(gormDB, secretStore)
	artifactStore := database.ProvideArtifactStore(gormDB)
	repoGitInfoView := database.ProvideRepoGitInfoView(gormDB)
	repoGitInfoCache := cache.ProvideRepoGitInfoCache(repoGitInfoView)
	listService := pullreq.ProvideListService(transactor, gitInterface, authorizer, spaceStore, repoStore, repoGitInfoCache, pullReqStore, checkStore, labelService, protectionManager)
	exporterRepository, err := exporter.ProvideSpaceExporter(provider, gitInterface, repoStore, jobScheduler, executor, encrypter, streamer)
	if err != nil {
		return nil, err
	}
	infraProviderResourceView := database.ProvideInfraProviderResourceView(gormDB)
	infraProviderResourceCache := cache.ProvideInfraProviderResourceCache(infraProviderResourceView)
	gitspaceConfigStore := database.ProvideGitspaceConfigStore(gormDB, principalInfoCache, infraProviderResourceCache)
	gitspaceInstanceStore := database.ProvideGitspaceInstanceStore(gormDB)
	infraProviderResourceStore := database.ProvideInfraProviderResourceStore(gormDB)
	infraProviderConfigStore := database.ProvideInfraProviderConfigStore(gormDB)
	infraProviderTemplateStore := database.ProvideInfraProviderTemplateStore(gormDB)
	dockerConfig, err := server.ProvideDockerConfig(config)
	if err != nil {
		return nil, err
	}
	dockerClientFactory := infraprovider.ProvideDockerClientFactory(dockerConfig)
	eventsReporter, err := events3.ProvideReporter(eventsSystem)
	if err != nil {
		return nil, err
	}
	dockerProvider := infraprovider.ProvideDockerProvider(dockerConfig, dockerClientFactory, eventsReporter)
	factory := infraprovider.ProvideFactory(dockerProvider)
	infraproviderService := infraprovider2.ProvideInfraProvider(transactor, infraProviderResourceStore, infraProviderConfigStore, infraProviderTemplateStore, factory, spaceStore)
	gitspaceService := gitspace.ProvideGitspace(transactor, gitspaceConfigStore, gitspaceInstanceStore, spaceStore, infraproviderService)
	spaceController := space.ProvideController(config, transactor, provider, streamer, spaceIdentifier, authorizer, spacePathStore, pipelineStore, secretStore, connectorStore, templateStore, spaceStore, repoStore, principalStore, artifactStore, repoController, membershipStore, listService, repository, exporterRepository, resourceLimiter, publicaccessService, auditService, gitspaceService, labelService, instrumentService, aiStore, executionStore)
	reporter2, err := events4.ProvideReporter(eventsSystem)
	if err != nil {
		return nil, err
	}
	pipelineController := pipeline.ProvideController(repoStore, triggerStore, authorizer, pipelineStore, reporter2)
	secretController := secret.ProvideController(encrypter, secretStore, authorizer, spaceStore)
	triggerController := trigger.ProvideController(authorizer, triggerStore, pipelineStore, repoStore)
	scmService := connector.ProvideSCMConnectorHandler(secretStore)
	connectorService := connector.ProvideConnectorHandler(secretStore, scmService)
	connectorController := connector2.ProvideController(connectorStore, connectorService, authorizer, spaceStore)
	templateController := template.ProvideController(templateStore, authorizer, spaceStore)
	pluginController := plugin.ProvideController(pluginStore)
	pullReqActivityStore := database.ProvidePullReqActivityStore(gormDB, principalInfoCache)
	codeCommentView := database.ProvideCodeCommentView(gormDB)
	pullReqReviewStore := database.ProvidePullReqReviewStore(gormDB)
	pullReqReviewerStore := database.ProvidePullReqReviewerStore(gormDB, principalInfoCache)
	userGroupReviewersStore := database.ProvideUserGroupReviewerStore(gormDB, principalInfoCache, userGroupStore)
	pullReqFileViewStore := database.ProvidePullReqFileViewStore(gormDB)
	reporter3, err := events5.ProvideReporter(eventsSystem)
	if err != nil {
		return nil, err
	}
	migrator := codecomments.ProvideMigrator(gitInterface)
	readerFactory, err := events6.ProvideReaderFactory(eventsSystem)
	if err != nil {
		return nil, err
	}
	eventsReaderFactory, err := events5.ProvideReaderFactory(eventsSystem)
	if err != nil {
		return nil, err
	}
	pullreqService, err := pullreq.ProvideService(ctx, config, readerFactory, eventsReaderFactory, reporter3, gitInterface, repoGitInfoCache, repoStore, pullReqStore, pullReqActivityStore, principalInfoCache, codeCommentView, migrator, pullReqFileViewStore, pubSub, provider, streamer)
	if err != nil {
		return nil, err
	}
	pullReq := migrate.ProvidePullReqImporter(provider, gitInterface, principalStore, spaceStore, repoStore, pullReqStore, pullReqActivityStore, labelStore, labelValueStore, pullReqLabelAssignmentStore, transactor, mutexManager)
	pullreqController := pullreq2.ProvideController(transactor, provider, authorizer, auditService, pullReqStore, pullReqActivityStore, codeCommentView, pullReqReviewStore, pullReqReviewerStore, repoStore, principalStore, userGroupStore, userGroupReviewersStore, principalInfoCache, pullReqFileViewStore, membershipStore, checkStore, aiStore, gitInterface, reporter3, migrator, pullreqService, listService, protectionManager, streamer, codeownersService, lockerLocker, pullReq, labelService, instrumentService, searchService)
	webhookConfig := server.ProvideWebhookConfig(config)
	webhookStore := database.ProvideWebhookStore(gormDB)
	webhookExecutionStore := database.ProvideWebhookExecutionStore(gormDB)
	urlProvider := webhook.ProvideURLProvider(ctx)
	webhookService, err := webhook.ProvideService(ctx, webhookConfig, transactor, readerFactory, eventsReaderFactory, webhookStore, webhookExecutionStore, spaceStore, aiStore, repoStore, pullReqStore, pullReqActivityStore, provider, principalStore, gitInterface, encrypter, labelStore, settingsService, urlProvider, labelValueStore)
	if err != nil {
		return nil, err
	}
	preprocessor := webhook2.ProvidePreprocessor()
	webhookController := webhook2.ProvideController(authorizer, spaceStore, repoStore, webhookService, encrypter, preprocessor)
	reporter4, err := events6.ProvideReporter(eventsSystem)
	if err != nil {
		return nil, err
	}
	preReceiveExtender, err := githook.ProvidePreReceiveExtender()
	if err != nil {
		return nil, err
	}
	updateExtender, err := githook.ProvideUpdateExtender()
	if err != nil {
		return nil, err
	}
	postReceiveExtender, err := githook.ProvidePostReceiveExtender()
	if err != nil {
		return nil, err
	}
	githookController := githook.ProvideController(authorizer, principalStore, repoStore, reporter4, reporter, reporter3, gitInterface, pullReqStore, provider, protectionManager, clientFactory, resourceLimiter, settingsService, preReceiveExtender, updateExtender, postReceiveExtender, codeownersService, pullReqReviewerStore)
	serviceaccountController := serviceaccount.NewController(principalUID, authorizer, principalStore, spaceStore, repoStore, tokenStore)
	principalController := principal.ProvideController(principalStore, authorizer)
	usergroupController := usergroup2.ProvideController(userGroupStore, spaceStore, authorizer, searchService)
	v := check2.ProvideCheckSanitizers()
	checkController := check2.ProvideController(transactor, authorizer, repoStore, checkStore, gitInterface, v)
	systemController := system.NewController(principalStore, config)
	blobConfig, err := server.ProvideBlobStoreConfig(config)
	if err != nil {
		return nil, err
	}
	blobStore, err := blob.ProvideStore(ctx, blobConfig)
	if err != nil {
		return nil, err
	}
	uploadController := upload.ProvideController(authorizer, repoStore, blobStore)
	searcher := keywordsearch.ProvideSearcher(localIndexSearcher)
	keywordsearchController := keywordsearch2.ProvideController(authorizer, searcher, repoController, spaceController)
	artifactConfig := server.ProvideArtifactConfig(config)
	contentStorage, err := artifact.ProvideArtifactLoadStorage(ctx, artifactConfig, storageConfig)
	if err != nil {
		return nil, err
	}
	artifactgcService, err := artifactgc.ProvideArtifactSweepSvc(transactor, artifactStore, contentStorage, settingsService, jobScheduler, executor, streamer)
	if err != nil {
		return nil, err
	}
	controllerController := controller.ProvideArtifactController(transactor, provider, authorizer, artifactStore, spaceStore, contentStorage, settingsService, artifactgcService)
	executionManager := manager.ProvideExecutionManager(config, executionStore, pipelineStore, provider, streamer, fileService, converterService, logStore, logStream, checkStore, repoStore, schedulerScheduler, secretStore, stageStore, stepStore, principalStore, publicaccessService, reporter2)
	runnerController := runner.ProvideController(transactor, authorizer, executionManager, provider)
	infraproviderController := infraprovider3.ProvideController(authorizer, spaceStore, infraproviderService)
	reporter5, err := events7.ProvideReporter(eventsSystem)
	if err != nil {
		return nil, err
	}
	gitnessSCM := scm.ProvideGitnessSCM(repoStore, gitInterface, tokenStore, principalStore, provider)
	genericSCM := scm.ProvideGenericSCM()
	scmFactory := scm.ProvideFactory(gitnessSCM, genericSCM)
	scmSCM := scm.ProvideSCM(scmFactory)
	infraProvisionedStore := database.ProvideInfraProvisionedStore(gormDB)
	infrastructureConfig := server.ProvideGitspaceInfraProvisionerConfig(config)
	infraProvisioner := infrastructure.ProvideInfraProvisionerService(infraProviderConfigStore, infraProviderResourceStore, factory, infraProviderTemplateStore, infraProvisionedStore, infrastructureConfig)
	statefulLogger := logutil.ProvideStatefulLogger(logStream)
	gitService := git2.ProvideGitServiceImpl()
	userService := user2.ProvideUserServiceImpl()
	containerOrchestrator := container.ProvideEmbeddedDockerOrchestrator(dockerClientFactory, statefulLogger, gitService, userService)
	orchestratorConfig := server.ProvideGitspaceOrchestratorConfig(config)
	vsCodeConfig := server.ProvideIDEVSCodeConfig(config)
	vsCode := ide.ProvideVSCodeService(vsCodeConfig)
	vsCodeWebConfig := server.ProvideIDEVSCodeWebConfig(config)
	vsCodeWeb := ide.ProvideVSCodeWebService(vsCodeWebConfig)
	passwordResolver := secret2.ProvidePasswordResolver()
	resolverFactory := secret2.ProvideResolverFactory(passwordResolver)
	orchestratorOrchestrator := orchestrator.ProvideOrchestrator(scmSCM, infraProviderResourceStore, infraProvisioner, containerOrchestrator, reporter5, orchestratorConfig, vsCode, vsCodeWeb, resolverFactory)
	gitspaceEventStore := database.ProvideGitspaceEventStore(gormDB)
	gitspaceController := gitspace2.ProvideController(transactor, authorizer, infraproviderService, gitspaceConfigStore, gitspaceInstanceStore, spaceStore, reporter5, orchestratorOrchestrator, gitspaceEventStore, statefulLogger, scmSCM, repoStore, gitspaceService)
	rule := migrate.ProvideRuleImporter(ruleStore, transactor, principalStore)
	migrateWebhook := migrate.ProvideWebhookImporter(webhookConfig, transactor, webhookStore)
	migrateLabel := migrate.ProvideLabelImporter(transactor, labelStore, labelValueStore, spaceStore)
	migrateController := migrate2.ProvideController(authorizer, publicaccessService, gitInterface, provider, pullReq, rule, migrateWebhook, migrateLabel, resourceLimiter, auditService, repoIdentifier, transactor, spaceStore, repoStore)
	registry, err := capabilities.ProvideCapabilities()
	if err != nil {
		return nil, err
	}
	capabilitiesController := capabilities2.ProvideController(registry)
	intelligence, err := aiagent.ProvideAiAgent(authorizer, registry, capabilitiesController)
	if err != nil {
		return nil, err
	}
	slack, err := messaging.ProvideSlack(repoStore, gitInterface)
	if err != nil {
		return nil, err
	}
	aiagentController := aiagent2.ProvideController(authorizer, intelligence, repoStore, pipelineStore, executionStore, gitInterface, provider, slack)
	openapiService := openapi.ProvideOpenAPIService()
	routerRouter := router.ProvideRouter(ctx, config, principalStore, authenticator, repoController, reposettingsController, executionController, logsController, spaceController, pipelineController, secretController, triggerController, connectorController, templateController, pluginController, pullreqController, webhookController, githookController, gitInterface, serviceaccountController, userController, principalController, usergroupController, checkController, systemController, uploadController, keywordsearchController, controllerController, runnerController, infraproviderController, gitspaceController, migrateController, aiagentController, capabilitiesController, provider, openapiService, artifactStore, repoStore, contentStorage)
	serverServer := server2.ProvideServer(config, routerRouter)
	publickeyService := publickey.ProvidePublicKey(publicKeyStore, principalInfoCache)
	sshServer := ssh.ProvideServer(config, publickeyService, repoController)
	client := manager.ProvideExecutionClient(executionManager, provider, config)
	resolverManager := resolver.ProvideResolver(config, pluginStore, templateStore, executionStore, repoStore)
	stageDynamicEnvProvider := extend.ProvideDynamicStageProvider(pipelineStorage, stageStore)
	runnerRunner, err := runner2.ProvideExecutionRunner(config, client, resolverManager, stageDynamicEnvProvider)
	if err != nil {
		return nil, err
	}
	poller := runner2.ProvideExecutionPoller(runnerRunner, client)
	triggerConfig := server.ProvideTriggerConfig(config)
	triggerService, err := trigger2.ProvideService(ctx, triggerConfig, triggerStore, commitService, pullReqStore, repoStore, pipelineStore, triggererTriggerer, readerFactory, eventsReaderFactory)
	if err != nil {
		return nil, err
	}
	systemService := system2.ProvideService(settingsService)
	collector, err := metric.ProvideCollector(config, principalStore, repoStore, pipelineStore, executionStore, jobScheduler, executor, gitspaceConfigStore, systemService)
	if err != nil {
		return nil, err
	}
	sizeCalculator, err := repo2.ProvideCalculator(config, gitInterface, repoStore, jobScheduler, executor)
	if err != nil {
		return nil, err
	}
	readerFactory2, err := events2.ProvideReaderFactory(eventsSystem)
	if err != nil {
		return nil, err
	}
	repoService, err := repo2.ProvideService(ctx, config, reporter, readerFactory2, repoStore, provider, gitInterface, lockerLocker)
	if err != nil {
		return nil, err
	}
	cleanupConfig := server.ProvideCleanupConfig(config)
	cleanupService, err := cleanup.ProvideService(cleanupConfig, jobScheduler, executor, webhookExecutionStore, tokenStore, repoStore, repoController, controllerController)
	if err != nil {
		return nil, err
	}
	mailerMailer := mailer.ProvideMailClient(config)
	notificationClient := notification.ProvideMailClient(mailerMailer)
	notificationConfig := server.ProvideNotificationConfig(config)
	notificationService, err := notification.ProvideNotificationService(ctx, notificationClient, notificationConfig, eventsReaderFactory, pullReqStore, repoStore, principalInfoView, principalInfoCache, pullReqReviewerStore, pullReqActivityStore, spacePathStore, provider)
	if err != nil {
		return nil, err
	}
	keywordsearchConfig := server.ProvideKeywordSearchConfig(config)
	keywordsearchService, err := keywordsearch.ProvideService(ctx, keywordsearchConfig, readerFactory, readerFactory2, repoStore, indexer)
	if err != nil {
		return nil, err
	}
	gitspaceeventConfig := server.ProvideGitspaceEventConfig(config)
	readerFactory3, err := events7.ProvideReaderFactory(eventsSystem)
	if err != nil {
		return nil, err
	}
	gitspaceeventService, err := gitspaceevent.ProvideService(ctx, gitspaceeventConfig, readerFactory3, gitspaceEventStore)
	if err != nil {
		return nil, err
	}
	readerFactory4, err := events3.ProvideReaderFactory(eventsSystem)
	if err != nil {
		return nil, err
	}
	gitspaceinfraeventService, err := gitspaceinfraevent.ProvideService(ctx, gitspaceeventConfig, readerFactory4, orchestratorOrchestrator, gitspaceService, reporter5)
	if err != nil {
		return nil, err
	}
	gitspaceServices := services.ProvideGitspaceServices(gitspaceeventService, infraproviderService, gitspaceService, gitspaceinfraeventService)
	consumer, err := instrument.ProvideGitConsumer(ctx, config, readerFactory, repoStore, principalInfoCache, instrumentService)
	if err != nil {
		return nil, err
	}
	repositoryCount, err := instrument.ProvideRepositoryCount(ctx, config, instrumentService, repoStore, jobScheduler, executor)
	if err != nil {
		return nil, err
	}
	servicesServices := services.ProvideServices(webhookService, pullreqService, triggerService, jobScheduler, collector, sizeCalculator, repoService, cleanupService, notificationService, keywordsearchService, gitspaceServices, instrumentService, consumer, repositoryCount)
	serverSystem := server.NewSystem(bootstrapBootstrap, serverServer, sshServer, poller, resolverManager, servicesServices)
	return serverSystem, nil
}
